### PR TITLE
docs: update contributions info

### PR DESCRIPTION
**Pull request by catouberos**
Please look at the changes and see if there's any question. Thank you.

### CODE REVIEW

**Review by MKhoaaa — APPROVED** [review]
Thank you so much for this contributions reevaluation

**Comment by catouberos** [comment]
> Thank you so much for this contributions reevaluation

No problem, but in the future if there's any problem, please tell the team in advance T_T

**Review by HippityHarry — APPROVED** [review]
well done every one

**Review by sonTungN — COMMENTED** [review]
"quality of life changes" :))

**Pull request merged**
